name: build and deploy

on:
  push:
    branch: [ master ]
  pull_request:
    branch: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: 'node_modules'
          key: hash-${{ hashFiles('yarn.lock') }}
      - name: install deps
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: webroot
          path: build/
  deploy:
    needs: [build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: webroot
          path: build/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: x.twidere.com

